### ISSUE TITLE
Fix authorization component

### ISSUE THREAD

**Issue by pavelmakarets** [Point2Point/Chess#24]
![image](https://user-images.githubusercontent.com/21967236/61117112-87b3b400-a49e-11e9-9742-a5100a517e37.png)
там косяк, два одиноковых роутинга
![image](https://user-images.githubusercontent.com/21967236/61117201-ae71ea80-a49e-11e9-922d-360ea2f78fc7.png)
не работает как модалка
![image](https://user-images.githubusercontent.com/21967236/61117466-3d7f0280-a49f-11e9-9ad2-e06dcabbaf3e.png)
нам не нужна папка view, добавляй все компоненты в папку comonents

**Comment by pavelmakarets** [comment]
Настрой за одно роутинги нормально,
Login(пока при любом login и pass, чтоб переходило) -> Game

**Comment by akryshtopchyk** [comment]
исправил в таске #20
